# Generated by Django 3.2.5 on 2021-07-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='Stu_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
